### PR TITLE
Makefile should support v2 package changes

### PR DESCRIPTION
**Pull request by sujaisd**
Found the build script failed due to wrong directory path error.

CODE should point to the new v2/cmd package.

Followed the steps in the GCP Documentation [https://cloud.google.com/binary-authorization/docs/creating-attestations-voucher]
```
go build -o build/voucher_server -v ./cmd/voucher_server
stat /go/src/github.com/grafeas/voucher/cmd/voucher_server: directory not found
make: *** [Makefile:77: voucher_server] Error 1
```

### CODE REVIEW

**Comment by sujaisd** [comment]
@googlebot I signed it!

**Review by catherinejones — APPROVED** [review]

**Comment by catherinejones** [comment]
Looks good to me, thank you @sujaisd! Once CI finishes please feel free to "Squash and Merge"!

**Review by rxbchen — APPROVED** [review]
👍

**Comment by sujaisd** [comment]
Someone with write access should squash and merge it.

**Comment by rxbchen** [comment]
✅

**Pull request merged**
